Repository Quillan13/bracket-app, pull requests merged in 2019-12, with the labels that each got.

#10 added brakcet css and working build your own bracked for 8 teams, **i…
  next.config.js
  package-lock.json
  package.json
  pages/Bracket.tsx
  pages/testB.tsx
Labels: bug, feature

#12 redeploy try
  pages/Bracket.tsx
  pages/bracket.css
  pages/select8.tsx
Labels: bug, feature

#13 Q
  pages/Bracket.tsx
  pages/bracketDisplay.css
  pages/index.tsx
  pages/select16.tsx
  pages/select4.tsx
  pages/select8.tsx
Labels: feature

#15 Q
  package-lock.json
  pages/Bracket.tsx
  pages/bracketDisplay.css
  pages/select16.tsx
  pages/select32.tsx
  pages/select8.tsx
Labels: feature

#19 Fixed issues with bracket styling
  pages/Bracket.tsx
  pages/select128.tsx
  pages/select16.tsx
  pages/select32.tsx
  pages/select4.tsx
  pages/select64.tsx
  pages/select8.tsx
  styles/bracketDisplay.css
Labels: bug

#20 test select 4
  pages/Bracket.tsx
  pages/select4.tsx
  utilities/Round1.tsx
Labels: documentation

#24 css fix
  data/DisneyAnimatedFilms.ts
  styles/bracketDisplay.css
Labels: improvement

#25 Temp data on Disney Bracket
  pages/Brackets/DisneyAnimatedMovies.tsx
  pages/index.tsx
Labels: feature

#26 Q
  data/DisneyAnimatedFilms.ts
  pages/Brackets/DisneyAnimatedMovies.tsx
Labels: improvement

#30 Q
  data/DisneyAnimatedFilms.ts
  pages/Brackets/DisneyAnimatedMovies.tsx
  utilities/Championship.tsx
  utilities/Match.tsx
  utilities/SemiFinal.tsx
Labels: improvement
