Repository Quillan13/bracket-app, pull requests merged in 2020-01, with the labels that each got.

#31 Q
  components/BracketView.tsx
  components/nav.js
  pages/Brackets/DisneyAnimatedMovies.tsx
  public/favicon.ico
  styles/bracketDisplay.css
  types/Bracket.ts
  types/BracketMatch.ts
  types/BracketParticipant.ts
  utilities/Match.tsx
Labels: feature

#32 deleted files
  utilities/BracketGenerator.ts
  utilities/Number.Utility.ts
Labels: improvement

#34 Q
  pages/Brackets/DisneyAnimatedMovies.tsx
  pages/select128.tsx
  pages/select16.tsx
  pages/select32.tsx
  pages/select4.tsx
  pages/select64.tsx
  pages/select8.tsx
  utilities/Championship.tsx
  utilities/Match.tsx
  utilities/SemiFinal.tsx
Labels: bug, feature, improvement

#35 added syling for button to be a little nicer **Still Not Perfect**
  styles/bracketDisplay.css
  utilities/Match.tsx
Labels: improvement

#36 adding google authentication
  package-lock.json
  package.json
  pages/LoginPage.tsx
  pages/index.tsx
  styles/LoginPage.css
Labels: feature, improvement

#37 Q
  pages/LoginPage.tsx
Labels: improvement

#38 test 2
  pages/LoginPage.tsx
Labels: improvement

#39 test 3
  pages/LoginPage.tsx
Labels: improvement

#40 last try
  pages/LoginPage.tsx
Labels: improvement

#43 added Dreamworks bracket and changed landing page to LoginPage
  data/Dreamworks Animated films.json
  data/DreamworksAnimatedFilms.ts
  pages/Brackets/DreamworksAnimatedMovies.tsx
  pages/Home.tsx
  pages/LoginPage.tsx
  pages/index.tsx
Labels: feature, improvement

#45 changed Bracket Size Drop Down
  pages/Bracket.tsx
Labels: bug, improvement

#48 moving name value to next round **broken**
  pages/Brackets/DisneyAnimatedMovies.tsx
  utilities/Match.tsx
Labels: bug, improvement

#50 Q
  data/DisneyAnimatedFilms.ts
  pages/Brackets/DisneyAnimatedMovies.tsx
  utilities/Match.tsx
Labels: bug, improvement

#51 Feature/create react app conversion
  .github/workflows/AppServiceDeployment.yml
  .gitignore
  ReadMe.md
  next-env.d.ts
  next.config.js
  package-lock.json
  package.json
  pages/Bracket.tsx
  pages/Brackets/DisneyAnimatedMovies.tsx
  pages/Brackets/DreamworksAnimatedMovies.tsx
  pages/Home.tsx
  pages/index.tsx
  pages/select128.tsx
  pages/select16.tsx
  pages/select32.tsx
  pages/select4.tsx
  pages/select64.tsx
  pages/select8.tsx
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/@Types/react-app-env.d.ts
  src/App.spec.tsx
  src/App.tsx
  src/Components/Championship.tsx
  src/Components/Match.tsx
  src/Components/SemiFinal.tsx
  src/Data/Disney Animated Films.json
  src/Data/DisneyAnimatedFilms.ts
  src/Data/Dreamworks Animated films.json
  src/Data/DreamworksAnimatedFilms.ts
  src/Pages/Brackets/CustomBracket.tsx
  src/Pages/Brackets/DisneyAnimatedMovies.tsx
  src/Pages/Brackets/DreamworksAnimatedMovies.tsx
  src/Pages/Brackets/index.tsx
  src/Pages/Home.tsx
  src/Pages/select128.tsx
  src/Pages/select16.tsx
  src/Pages/select32.tsx
  src/Pages/select4.tsx
  src/Pages/select64.tsx
  src/Pages/select8.tsx
  src/Styles/BracketDisplay.css
  src/Styles/LoginPage.css
  src/Types/Page.ts
  src/Types/ServiceWorker.ts
  src/index.tsx
  src/setupTests.ts
  tsconfig.json
  utilities/Championship.tsx
  utilities/Match.tsx
  utilities/SemiFinal.tsx
  utilities/theme.js
Labels: feature, improvement

#52 Added Web Config to fix Routing
  public/web.config
Labels: bug

#55 Q
  ReadMe.md
  public/index.html
  public/vslogo192.png
  src/Components/Match.tsx
  src/Components/SemiFinal.tsx
  src/Pages/Brackets/DisneyAnimatedMovies.tsx
  src/Pages/Brackets/DreamworksAnimatedMovies.tsx
  src/Pages/select128.tsx
  src/Pages/select16.tsx
  src/Pages/select32.tsx
  src/Pages/select64.tsx
  src/Pages/select8.tsx
  src/react-app-env.d.ts
Labels: feature

#58 Google Authentication with Azure
  .github/workflows/AppServiceDeployment.yml
  .gitignore
  package-lock.json
  package.json
  src/Configs/AzureADConfig.ts
  src/Pages/Brackets/DisneyAnimatedMovies.tsx
  src/Pages/Home.tsx
  src/Services/AuthService.ts
Labels: feature

#59 Feature/winner checks
  src/Components/Match.tsx
  src/Components/SemiFinal.tsx
  src/Pages/Brackets/DisneyAnimatedMovies.tsx
Labels: feature

#61 updated Dreamworks bracket to have new features
  src/Pages/Brackets/DreamworksAnimatedMovies.tsx
Labels: Improvements

#63 corrected Aladdin spelling
  src/Data/Disney Animated Films.json
  src/Data/DisneyAnimatedFilms.ts
Labels: Improvements

#64 user input on select 4 rough draft
  src/Pages/select4.tsx
Labels: feature

#65 Added Redux and App Bar
  package-lock.json
  package.json
  src/App.tsx
  src/Components/BracketAppBar.tsx
  src/Pages/Home.tsx
  src/Services/LocalStorageService.ts
  src/Store/Authentication/Actions.ts
  src/Store/Authentication/Reducer.ts
  src/Store/Authentication/State.ts
  src/Store/Authentication/index.ts
  src/Store/index.ts
  src/Theme.ts
  src/index.tsx
Labels: Improvements, feature

#66 fix build
  src/App.spec.tsx
Labels: bug

#67 side bar styling
  src/App.tsx
  src/Components/AppDrawer.tsx
  src/Components/BracketAppBar.tsx
  src/Components/Layout.tsx
Labels: Improvements, feature

#68 side bar stuff
  src/App.tsx
  src/Components/AppDrawer.tsx
  src/Pages/Home.tsx
  src/Pages/PreMade.tsx
Labels: Improvements, feature, help wanted

#70 Q
  src/Pages/select4.tsx
Labels: Improvements

#71 Feature/user inputs
  src/Components/Inputs/Make.tsx
  src/Pages/Brackets/CustomBracket.tsx
  src/Pages/select4.tsx
Labels: Improvements, feature

#72 user input works for all 128 inputs, need to write functionality to r…
  package-lock.json
  src/Components/Inputs/Make.tsx
  src/Pages/select4.tsx
Labels: Improvements, feature

#73 Q
  src/Components/AppDrawer.tsx
  src/Components/Inputs/Make.tsx
  src/Pages/select128.tsx
  src/Pages/select16.tsx
  src/Pages/select32.tsx
  src/Pages/select64.tsx
  src/Pages/select8.tsx
Labels: Improvements, feature

#75 user input fields work
  src/Components/AppDrawer.tsx
  src/Components/Inputs/Make.tsx
  src/Pages/Home.tsx
Labels: feature

#76 select 4 and select 8 userinput and array mapping complete
  src/Components/Inputs/Make.tsx
  src/Components/Match.tsx
  src/Components/SemiFinal.tsx
  src/Pages/Brackets/DisneyAnimatedMovies.tsx
  src/Pages/select4.tsx
  src/Pages/select8.tsx
Labels: Improvements, feature

#78 Q
  src/App.tsx
  src/Pages/Home.tsx
Labels: Improvements, bug, feature

#79 added usermenu instead of logout button
  src/App.tsx
  src/Components/BracketAppBar.tsx
  src/Components/UserMenu.tsx
  src/Pages/select4.tsx
Labels: Improvements, feature
